name: travel_wisata_lokal
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  # Utilitas
  cupertino_icons: ^1.0.2
  intl: ^0.20.2 # Untuk format tanggal
  permission_handler: ^11.3.1 # Untuk minta izin lokasi

  # Database (Tugas Anggota 4)
  sqflite: ^2.3.0
  path: ^1.8.3

  # Maps & Lokasi (Tugas Anggota 4 & 5)
  google_maps_flutter: ^2.5.0

  # Gambar (Tugas Anggota 3 & 5)
  image_picker: ^1.0.4
  uuid: ^4.5.2
  shared_preferences: ^2.5.3
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo.png" # ikon utama (1024x1024)

  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/logo/icon.png"

flutter:
  uses-material-design: true

  fonts:
    - family: AppFont
      fonts:
        - asset: assets/fonts/MyFont-Regular.ttf
        - asset: assets/fonts/MyFont-Bold.ttf
          weight: 700
